cyber_wary/urls.py
#
# GNU General Public License v3.0
# CyberWary - <https://github.com/metallicgloss/CyberWary>
# Copyright (C) 2022 - William P - <hello@metallicgloss.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

# Module/Library Import
from django.urls import path, include

urlpatterns = [
    path(
        '',
        include('cyber_wary_site.urls')
    ),

    path(
        'portal/',
        include('cyber_wary_portal.urls.portal')
    ),

    path(
        'portal/api/',
        include('cyber_wary_portal.urls.api')
    ),
]

cyber_wary_portal/models/scan_credential.py
#
# GNU General Public License v3.0
# CyberWary - <https://github.com/metallicgloss/CyberWary>
# Copyright (C) 2022 - William P - <hello@metallicgloss.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

# Module/Library Import
from cyber_wary_portal.models.core import *
from django.db import models


# --------------------------------------------------------------------------- #
#                                                                             #
#                              CREDENTIAL MODELS                              #
#                                                                             #
#     Models associated with credential scan component of a system scan.      #
#                                                                             #
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
#                                   CONTENTS                                  #
# --------------------------------------------------------------------------- #
#                                                                             #
#                        1. Credential Models                                 #
#                            1.1 Browser                                      #
#                            1.2 Credential Scan                              #
#                            1.3 Credential Record                            #
#                                                                             #
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
#                            1. Credential Models                             #
# --------------------------------------------------------------------------- #
#                              1.1 Browser Class                              #
# --------------------------------------------------------------------------- #

class Browser(DefaultFields):
    # Model to store the name of the individual browser a credential is associated with.
    name = models.CharField(
        max_length=64,
        null=True,
        help_text="The name of the browser"
    )


# --------------------------------------------------------------------------- #
#                          1.2 Credential Scan Class                          #
# --------------------------------------------------------------------------- #

class CredentialScan(DefaultFields):
    # Model to store the store the status of credential import as part of a scan.

    # Available status settings for a credential import.
    class ScanStatus(models.IntegerChoices):
        PENDING = 1
        IN_PROGRESS = 2
        PARTIALLY_COMPLETED = 3
        COMPLETED = 4

    scan_record = models.ForeignKey(
        ScanRecord,
        on_delete=models.CASCADE,
        help_text="The scan record that the credential scan group is associated with."
    )

    progress = models.IntegerField(
        choices=ScanStatus.choices,
        default=ScanStatus.PENDING,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ],
        help_text="The current progress/status of the credential processing."
    )


# --------------------------------------------------------------------------- #
#                         1.3 Credential Record Class                         #
# --------------------------------------------------------------------------- #

class Credential(DefaultFields):
    # Model to store an individual credential captured from a scanned device.

    # Available rating for password security.
    class SecurityRating(models.IntegerChoices):
        VERY_WEAK = 1
        WEAK = 2
        MEDIUM = 3
        STRONG = 4
        VERY_STRONG = 5

    credential_scan = models.ForeignKey(
        CredentialScan,
        on_delete=models.CASCADE,
        help_text="The credential scan group that the credential is associated with."
    )

    url = models.CharField(
        max_length=128,
        null=True,
        help_text="The URL that the credential is associated with."
    )

    browser = models.ForeignKey(
        Browser,
        on_delete=models.CASCADE,
        help_text="The browser that the credential has been captured from."
    )

    storage = models.DateTimeField(
        null=True,
        help_text="The date/time that the credential was created/stored."
    )

    username = models.CharField(
        max_length=64,
        null=True,
        help_text="The username/email address associated with the credential."
    )

    password_strength = models.IntegerField(
        choices=SecurityRating.choices,
        default=SecurityRating.MEDIUM,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ],
        help_text="The strength of the password associated with the credential."
    )

    filename = models.CharField(
        max_length=128,
        null=True,
        help_text="The filename on the system that the credential was captured from."
    )

    compromised = models.BooleanField(
        default=False,
        help_text="The flag to identify if the password has appeared in a data breach."
    )

    occurrence = models.IntegerField(
        default=0,
        help_text="The number of times that the password has been seen in a data breach."
    )

cyber_wary_portal/models/scan_software.py
#
# GNU General Public License v3.0
# CyberWary - <https://github.com/metallicgloss/CyberWary>
# Copyright (C) 2022 - William P - <hello@metallicgloss.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

# Module/Library Import
from cyber_wary_portal.models.core import *
from django.db import models


# --------------------------------------------------------------------------- #
#                                                                             #
#                               SOFTWARE MODELS                               #
#                                                                             #
#          Models associated the software check component of a scan.          #
#                                                                             #
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
#                                   CONTENTS                                  #
# --------------------------------------------------------------------------- #
#                                                                             #
#                   1. Public Definitions                                     #
#                       1.1 Common Platform Enumeration                       #
#                       1.2 Common Weakness Enumeration                       #
#                       1.3 Common Vulnerabilities and Exposures              #
#                       1.4 CVE References                                    #
#                       1.5 CVE Linked Weaknesses                             #
#                       1.6 CVE Linked Platforms                              #
#                   2. Software                                               #
#                       2.1 Publisher                                         #
#                       2.2 Installed Software                                #
#                                                                             #
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
#                            1. Public Definitions                            #
# --------------------------------------------------------------------------- #
#                    1.1 Common Platform Enumeration Class                    #
# --------------------------------------------------------------------------- #

class CPE(DefaultFields):
    # Model to store the identifier for a CPE.

    identifier = models.CharField(
        max_length=192,
        null=False,
        unique=True,
        help_text="The identifier for the CPE."
    )

    title = models.CharField(
        max_length=192,
        null=True,
        help_text="The title/name for the software referenced by the CPE."
    )


# --------------------------------------------------------------------------- #
#                    1.2 Common Weakness Enumeration Class                    #
# --------------------------------------------------------------------------- #

class CWE(DefaultFields):
    # Model to store the identifier for a CWE.

    identifier = models.IntegerField(
        default=0,
        blank=False,
        unique=True,
        help_text="The identifier for the CWE."
    )

    name = models.CharField(
        max_length=192,
        null=True,
        help_text="The name given to the CWE."
    )

    description = models.CharField(
        max_length=512,
        null=True,
        help_text="The description given to the CWE."
    )


# --------------------------------------------------------------------------- #
#                1.3 Common Vulnerabilities and Exposures Class               #
# --------------------------------------------------------------------------- #

class CVE(DefaultFields):
    # Model to store the identifier information surrounding a CVE.

    identifier = models.CharField(
        max_length=32,
        blank=False,
        unique=True,
        help_text="The identifier for the CVE."
    )

    assigner = models.CharField(
        max_length=64,
        null=True,
        help_text="The assigner for the CVE."
    )

    description = models.TextField(
        null=True,
        help_text="The description of the CVE."
    )

    cvss = models.CharField(
        max_length=64,
        null=True,
        help_text="The CVSS v3 vector string of the CVE."
    )

    published = models.DateTimeField(
        null=True,
        help_text="The date/time that the CVE was published."
    )


# --------------------------------------------------------------------------- #
#                             1.4 CVE References                              #
# --------------------------------------------------------------------------- #

class CVEReference(DefaultFields):
    # Model to store the links and references associated with a CVE.

    cve = models.ForeignKey(
        CVE,
        on_delete=models.CASCADE,
        help_text="The CVE that the reference is associated with."
    )

    url = models.TextField(
        null=True,
        help_text="The URL for the reference."
    )

    name = models.TextField(
        null=True,
        help_text="The name for the reference."
    )

    source = models.CharField(
        max_length=128,
        null=True,
        help_text="The source for the reference."
    )

    tags = models.CharField(
        max_length=128,
        null=True,
        help_text="The tags associated with the reference."
    )


# --------------------------------------------------------------------------- #
#                       1.5 CVE Linked Weaknesses Class                       #
# --------------------------------------------------------------------------- #

class CVEWeaknesses(DefaultFields):
    # Model to store the weaknesses related to a specific CVE.

    cve = models.ForeignKey(
        CVE,
        on_delete=models.CASCADE,
        help_text="The CVE that the weakness is associated with."
    )

    cwe = models.ForeignKey(
        CWE,
        on_delete=models.CASCADE,
        help_text="The weakness that the CVE is associated with."
    )


# --------------------------------------------------------------------------- #
#                       1.6 CVE Linked Platforms Class                        #
# --------------------------------------------------------------------------- #

class CVEMatches(models.Model):
    # Model to store the platforms/software associated with a specific CVE.

    cve = models.ForeignKey(
        CVE,
        on_delete=models.CASCADE,
        help_text="The CVE that the CPE is linked to."
    )

    cpe = models.ForeignKey(
        CPE,
        on_delete=models.CASCADE,
        help_text="The CPE that features the CVE."
    )


# --------------------------------------------------------------------------- #
#                                 2. Software                                 #
# --------------------------------------------------------------------------- #
#                             2.1 Publisher Class                             #
# --------------------------------------------------------------------------- #

class Publisher(DefaultFields):
    # Model to store names of publishers.

    name = models.CharField(
        max_length=128,
        null=True,
        help_text="The name of the publisher."
    )

    logo = models.CharField(
        max_length=256,
        null=True,
        help_text="The logo of the publisher."
    )

    website = models.CharField(
        max_length=256,
        null=True,
        help_text="The associated website of the publisher."
    )

# --------------------------------------------------------------------------- #
#                         2.2 Installed Software Class                        #
# --------------------------------------------------------------------------- #


class Software(DefaultFields):
    # Model to store details surrounding software installed on a device being scanned.

    scan_record = models.ForeignKey(
        ScanRecord,
        on_delete=models.CASCADE,
        help_text="The scan record that the software/installation is associated with."
    )

    name = models.CharField(
        max_length=128,
        null=True,
        help_text="The name given to the software (Name)."
    )

    version = models.CharField(
        max_length=32,
        null=True,
        help_text="The version of the software installed (DisplayVersion)."
    )

    version_major = models.CharField(
        max_length=8,
        null=True,
        help_text="The major version of the software installed (VersionMajor)."
    )

    version_minor = models.CharField(
        max_length=16,
        null=True,
        help_text="The minor version of the software installed (VersionMinor)."
    )

    publisher = models.ForeignKey(
        Publisher,
        on_delete=models.CASCADE,
        help_text="The publisher that the software is associated with (Publisher)."
    )

    cpe = models.ForeignKey(
        CPE,
        on_delete=models.CASCADE,
        default=None,
        null=True,
        help_text="The CPE associated with the application."
    )

    install_path = models.CharField(
        max_length=256,
        null=True,

cyber_wary_portal/templates/scan/report/components/browser_passwords.html
{% load subtract %}

{% comment %}
GNU General Public License v3.0
CyberWary - <https://github.com/metallicgloss/CyberWary>
Copyright (C) 2022 - William P - <hello@metallicgloss.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% if scan_record.scan.browser_passwords and scan_data.browser_passwords != None %}
    <div class="accordion-item">
        <!-- Accordion Tab Title -->
        <h2 class="accordion-header" id="heading-browser-passwords">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-browser-passwords" aria-expanded="false" aria-controls="collapse-browser-passwords">
                {% if scan_data.compromised > 0 %}
                    <i class="icofont-exclamation-tringle me-2 text-danger"></i>
                {% elif scan_data.weak > 0 %}
                    <i class="icofont-exclamation-tringle me-2 text-warning"></i>
                {% else %}
                    <i class="icofont-check-circled me-2 pt-1 text-success"></i>
                {% endif %}
                Browser Passwords
            </button>
        </h2>

        <div id="collapse-browser-passwords" class="accordion-collapse collapse" aria-labelledby="heading-browser-passwords" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
                <!-- Credentials Explainer -->
                <h5 class="mt-4">Credentials</h5>
                <p class="mb-4">Have excellent password hygiene? Store passwords securely in your browser rather than on paper? Your passwords are only as secure as your system, and anyone with access to your device can quickly view them all; if you're not using a password manager, this component will scan all passwords available on your system to check their strength and if they've been potentially compromised.</p>

                <!-- Credentials Metrics / Charts -->
                <div class="row">
                    <div class="col-xl-6">
                        <div id="usernames" style="margin:auto"></div>
                    </div>
                    <div class="col-xl-6">
                        <div id="compromised" style="margin:auto"></div>
                    </div>
                </div>

                <!-- Credentials List -->
                <h5 class="mt-5">Detected Credentials</h5>
                <table id="credentials" class="display pb-3 w-100">
                    <thead>
                        <tr>
                            <th class="py-2 desktop">URL</th>
                            <th class="py-2 desktop">Username</th>
                            <th class="py-2 desktop">Strength</th>
                            <th class="py-2 desktop">Compromised</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for credential in scan_data.browser_passwords %}
                            <tr>
                                <td>{{ credential.url|slice:":40" }}</td>
                                <td>
                                    <span class="payload-action" onclick="viewCredential('{{ credential.id }}')" data-toggle="tooltip" data-placement="top" title="Click for full record.">
                                        <i class="icofont-info-circle me-2"></i>{{ credential.username }}
                                    </span>
                                </td>
                                <td>
                                    {% if credential.password_strength != 5 %}
                                        <span class="text-warning">{{ credential.get_password_strength_display }}</span>
                                    {% else %}
                                        <span class="text-success">{{ credential.get_password_strength_display }}</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if credential.compromised %}
                                        <span class="text-danger"><i class="icofont-exclamation-tringle me-2"></i>Potentially Compromised</span>
                                    {% else %}
                                        Not Detected in Dataset
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <p class="pb-2"><small>Password breach data supplied by the <a href="https://haveibeenpwned.com/Passwords" class="text-success">Have I Been Pwned</a> project.</small></p>

                <!-- Accordion Controls -->
                <div class="nav-buttons mt-4">
                    <button class="back btn bg-primary text-white text-uppercase px-4 py-1">Prev</button>
                    <button class="next btn bg-success text-white text-uppercase px-4 py-1 float-end">Next</button>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Credential Popup Modal -->
    <div class="modal fade" id="credentialModal" tabindex="-1" aria-labelledby="credentialModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h5 class="modal-title">Credential Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <!-- Modal Body / Contents -->
                <div class="modal-body">
                    <div class="scan-info">
                        <!-- Credential Details -->
                        <p class="mb-1"><i class="icofont-ui-user me-2"></i>Username: <span id="credUsername"></span></p>
                        <p class="mb-1"><i class="icofont-chart-histogram me-2"></i>Password Strength: <span id="credStrength"></span></p>
                        <p class="mb-1"><i class="icofont-web me-2"></i>URL: <span id="credURL"></span></p>
                        <p class="mb-1"><i class="icofont-dashboard-web me-2"></i>Browser: <span id="credBrowser"></span></p>
                        <p class="mb-1"><i class="icofont-file-sql me-2"></i>Storage Location: <span id="credFilename"></span></p>

                        <!-- Horizontal Divider -->
                        <hr>
                        
                        <!-- Compromise Details -->
                        <p class="mb-1"><i class="icofont-danger-zone me-2"></i>Compromised: <span id="credCompromised"></span></p>
                        <p class="mb-1"><i class="icofont-pie-chart me-2"></i>Occurrence (Number of Times Seen in a Breach): <span id="credOccurrence"></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Credential dynamic variables
        var credentials = true
        var credentialURL = "{% url 'credential' %}"

        // Chart Dataset
        var usernameData = [
            {% for username in scan_data.usernames %}
                {
                    value: {{ username.username__count }},
                    name: '{{ username.username }}'
                },
            {% endfor %}
        ]

        var compromisedColor = {% if scan_data.compromised > 0 %}'#f54b4b'{% else %}'#272727'{% endif %}
        var compromisedValue = {{ scan_data.compromised }}
        var undetectedValue = {{ scan_data.browser_passwords.count|subtract:scan_data.compromised }}
    </script>
{% endif %}

cyber_wary_portal/templates/scan/report/components/system_users.html
{% comment %}
GNU General Public License v3.0
CyberWary - <https://github.com/metallicgloss/CyberWary>
Copyright (C) 2022 - William P - <hello@metallicgloss.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}
{% if scan_record.scan.system_users and scan_data.system_users.count != 0 %}
    <div class="accordion-item">
        <!-- Accordion Tab Title -->
        <h2 class="accordion-header" id="heading-system-users">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-system-users" aria-expanded="false" aria-controls="collapse-system-users">
                {% if scan_data.enabled_defaults > 0 or scan_data.system_users.count > 5 %}
                    <i class="icofont-exclamation-tringle me-2 text-warning"></i>
                {% else %}
                    <i class="icofont-check-circled me-2 pt-1 text-success"></i>
                {% endif %}
                System Users
            </button>
        </h2>

        <div id="collapse-system-users" class="accordion-collapse collapse" aria-labelledby="heading-system-users" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
                <!-- System User Explainer -->
                <h5 class="mt-4">User Accounts</h5>
                <p class="mb-4">This component reviews your current system settings to ensure that there are no enabled systems accounts and that your account settings are configured correctly; a check is also performed to ensure that user-created profiles have been converted to a Microsoft account to allow for easy local password bypass attacks to take place.</p>

                <!-- System User List -->
                <h5 class="mt-5">System Users</h5>
                <table id="system-users" class="display pb-3 w-100">
                    <thead>
                        <tr>
                            <th class="py-2 desktop">Name</th>
                            <th class="py-2 desktop">Type</th>
                            <th class="py-2 desktop">Last Login</th>
                            <th class="py-2 desktop">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in scan_data.system_users %}
                            <tr>
                                <td>{{ user.name }} {% if user.full_name %}({{ user.full_name }}){% endif %}</td>
                                <td>
                                    {% if user.name not in 'Administrator,DefaultAccount,Guest,WDAGUtilityAccount' and user.source != 2 %}
                                        <span class="text-warning" data-toggle="tooltip" data-placement="top" title="Account should be converted to a Microsoft login to improve security."><i class="icofont-info-circle me-1"></i>
                                    {% else %}
                                        <span class="text-success">
                                    {% endif %}
                                        {{ user.get_source_display }}
                                    </span>
                                </td>
                                <td>{% if user.last_logon %}{{ user.last_logon|date:"l jS F Y - H:i e" }}{% else %}Never Logged In{% endif %}</td>
                                <td>
                                    {% if user.name in 'Administrator,DefaultAccount,Guest,WDAGUtilityAccount' and user.enabled %}
                                        <span class="text-danger" data-toggle="tooltip" data-placement="top" title="Default system accounts should not be enabled."><i class="icofont-info-circle me-1"></i>
                                    {% else %}
                                        <span class="text-success">
                                    {% endif %}
                                            {% if user.enabled %}Enabled</span>{% else %}Disabled{% endif %}
                                        </span>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <!-- Accordion Controls -->
                <div class="nav-buttons mt-4">
                    <button class="back btn bg-primary text-white text-uppercase px-4 py-1">Prev</button>
                    <button class="next btn bg-success text-white text-uppercase px-4 py-1 float-end">Next</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}